### ISSUE TITLE
Increase of Decrease the size of Progress Bar...

### ISSUE THREAD

**Issue by aliraza96** [websoptimization/react-native-dashed-progress#15]
How can I Increase or Decrease the Size of the Progress Bar ?

**Comment by websoptimization** [comment]
@aliraza96 you can use radius props to increase or decrease the size of the progress bar like,

```
 <DashedProgress
          fill={60}
          strokeThickness={2}
          countBars={100}
          radius={70}
          divideEnabled={true}
          indicatorColor="blue"
          tooltipColor="blue"
  />
```

also you can review the example for better understanding

**Comment by aliraza96** [comment]
Can we make it semi-circle somehow ? I mean I want to display it like this

<img width="298" alt="Screenshot 2022-01-12 at 3 38 29 PM" src="https://user-images.githubusercontent.com/59387704/149124727-8317e354-2d54-434b-bd71-3dfd21c7131f.png">

**Comment by CodeGradientsProjects** [comment]
> @aliraza96 you can use radius props to increase or decrease the size of the progress bar like,
> 
> ```
>  <DashedProgress
>           fill={60}
>           strokeThickness={2}
>           countBars={100}
>           radius={70}
>           divideEnabled={true}
>           indicatorColor="blue"
>           tooltipColor="blue"
>   />
> ```
> 
> also you can review the example for better understanding

Can you please address to my other issues ? I really need to solve these.
